[profile.default]
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200
evm_version = "paris"

test = "forge-test"

libs = [
    "lib",
    "node_modules",
]
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@solidity-parser/=node_modules/@solidity-parser/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "wormhole/=lib/wormhole/ethereum/contracts",
    "wormhole-forge-sdk/=modules/src",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
